Update the release workflows
OpenZeppelin/defender-client pull request #471
Opened 2023-12-11 13:13 UTC by collins-w

- Refactor the release workflows following the publishing flow

2023-12-12 05:43 UTC, tirumerla requested changes
Added comments, need changes.

2023-12-12 05:43 UTC, tirumerla commented on .github/workflows/rc-push.yml
> -    if: needs.verify-packages.outputs.changed_packages > 0
You should keep this, this was removed to test the functionality

2023-12-12 05:43 UTC, tirumerla commented on .github/workflows/stable-publish.yml
> +  workflow_call: {}
keep on push branches here and remove workflow_dispatch, it is only for stable-push , this should detect the author and if the commit message has rc or not

2023-12-12 05:43 UTC, tirumerla commented on .github/workflows/stable-push.yml
>            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
Change this to use the pull request github action

2023-12-12 05:43 UTC, tirumerla commented on .github/workflows/stable-push.yml
> +    uses: ./.github/workflows/stable-publish.yml
We don't need this, please update similar to what we have in `rc-push.yaml`

2023-12-12 20:34 UTC, tirumerla requested changes

2023-12-13 07:04 UTC, collins-w commented on .github/workflows/stable-push.yml
> +
This was not intentional.

2023-12-13 07:17 UTC, tirumerla approved these changes
lgtm

2023-12-13 17:35 UTC, merged